### ISSUE TITLE
Build Failed since Updating to latest version of AdMob v1.3.9

### ISSUE THREAD

**Issue by FuseGamesLLC** [YoYoGames/GMEXT-AdMob#48]
I only have an issue when compiling for iOS but I am getting the following build error which seems to be a collision with my Firebase extension (or something is breaking before pod file runs properly). If I disable my AdMob extension I am able to build normally (or if I revert to my older version of AdMob). My IDE is v2024.2.0.132 and Runtime is v2024.2.0.163

Here's the bottom part of my build output:

```
    cd /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/steve/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos17.4-21E210-99a79c02cfa501706f5b564e46d84afe.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/steve/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wno-parentheses -Wswitch -Wno-unused-function -Wno-unused-lab
el -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body @/Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/a
rm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -include /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/PrecompiledHeaders/SharedPrecompiledHeaders/720127702450075207/pch.hpp -MMD -MT dependencies -MF /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/ext_AppTrackingTransparency.d --serialize-diagnostics /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/ext_AppTrackingTransparency.dia -c /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceT
apper/Game/iOSSource/ext_AppTrackingTransparency.mm -o /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/ext_AppTrackingTransparency.o
/Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSource/ext_AppTrackingTransparency.mm:24:7: warning: @available does not guard availability here; use if (@available) instead [-Wunsupported-availability-guard]
        if(!(@available(iOS 14.0, *)))
             ^
/Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSource/ext_AppTrackingTransparency.mm:36:7: warning: @available does not guard availability here; use if (@available) instead [-Wunsupported-availability-guard]
        if(!(@available(iOS 14.0, *)))
             ^
Compiled YYFirebaseCrashlytics.mm for arm64
    cd /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/steve/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos17.4-21E210-99a79c02cfa501706f5b564e46d84afe.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/steve/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wno-parentheses -Wswitch -Wno-unused-function -Wno-unused-lab
el -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body @/Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/a
rm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -include /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/PrecompiledHeaders/SharedPrecompiledHeaders/720127702450075207/pch.hpp -MMD -MT dependencies -MF /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/YYFirebaseCrashlytics.d --serialize-diagnostics /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/YYFirebaseCrashlytics.dia -c /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/i
OSSource/YYFirebaseCrashlytics.mm -o /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/YYFirebaseCrashlytics.o
In file included from /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSource/YYFirebaseCrashlytics.mm:2:
/Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSource/YYFirebaseCrashlytics.h:2:9: fatal error: 'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Compiled YYFirebaseAnalytics.mm for arm64
    cd /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/steve/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos17.4-21E210-99a79c02cfa501706f5b564e46d84afe.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/steve/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wno-parentheses -Wswitch -Wno-unused-function -Wno-unused-lab
el -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body @/Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/a
rm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -include /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/PrecompiledHeaders/SharedPrecompiledHeaders/720127702450075207/pch.hpp -MMD -MT dependencies -MF /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/YYFirebaseAnalytics.d --serialize-diagnostics /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/YYFirebaseAnalytics.dia -c /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSo
urce/YYFirebaseAnalytics.mm -o /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/YYFirebaseAnalytics.o
In file included from /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSource/YYFirebaseAnalytics.mm:2:
/Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSource/YYFirebaseAnalytics.h:2:9: fatal error: 'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiled WebViewGM.mm for arm64
    cd /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/steve/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos17.4-21E210-99a79c02cfa501706f5b564e46d84afe.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/steve/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wno-parentheses -Wswitch -Wno-unused-function -Wno-unused-lab
el -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body @/Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/a
rm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -include /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/PrecompiledHeaders/SharedPrecompiledHeaders/720127702450075207/pch.hpp -MMD -MT dependencies -MF /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/WebViewGM.d --serialize-diagnostics /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/WebViewGM.dia -c /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSource/WebViewGM.mm -o
 /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/WebViewGM.o
Compiled Vibration.mm for arm64
    cd /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/steve/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos17.4-21E210-99a79c02cfa501706f5b564e46d84afe.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/steve/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wno-parentheses -Wswitch -Wno-unused-function -Wno-unused-lab
el -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body @/Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/a
rm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -include /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/PrecompiledHeaders/SharedPrecompiledHeaders/720127702450075207/pch.hpp -MMD -MT dependencies -MF /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/Vibration.d --serialize-diagnostics /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/Vibration.dia -c /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSource/Vibration.mm -o
 /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/Vibration.o
Compiled VerifyStoreReceipt.mm for arm64
    cd /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/steve/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos17.4-21E210-99a79c02cfa501706f5b564e46d84afe.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/steve/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wno-parentheses -Wswitch -Wno-unused-function -Wno-unused-lab
el -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body @/Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/a
rm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -include /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/PrecompiledHeaders/SharedPrecompiledHeaders/720127702450075207/pch.hpp -MMD -MT dependencies -MF /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/VerifyStoreReceipt.d --serialize-diagnostics /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/VerifyStoreReceipt.dia -c /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSour
ce/VerifyStoreReceipt.mm -o /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/VerifyStoreReceipt.o
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/steve/Library/Developer/Xcode/DerivedData/IdleSpaceTapper-ermivedafwttrheazrsamcagmhdy/Build/Intermediates.noindex/ArchiveIntermediates/IdleSpaceTapper/IntermediateBuildFilesPath/IdleSpaceTapper.build/Release-iphoneos/IdleSpaceTapper.build/Objects-normal/arm64/YYFirebaseCrashlytics.o /Users/steve/GameMakerStudio2/GM_IOS/IdleSpaceTapper/IdleSpaceTapper/IdleSpaceTapper/Game/iOSSource/YYFirebaseCrashlytics.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'IdleSpaceTapper' from project 'IdleSpaceTapper')
(1 failure)
System.Exception: xcodebuild command exited with status 65
   at Igor.XCodeOutputReader.Process(TextWriter _out)
   at Igor.iOSBuilder.LaunchXcWorkspaceYYC()
   at Igor.iOSBuilder.Package()
Igor complete.
elapsed time 00:02:26.3850210s for command "/Users/Shared/GameMakerStudio2/Cache/runtimes/runtime-2024.2.0.163/bin/igor/osx/x64/Igor" -j=8  -options="/tmp/GameMakerStudio2/GMS2TEMP/build.bff" -v -- iOS Package started at 05/27/2024 21:37:41
FAILED: Package Program Complete
```

**Comment by FuseGamesLLC** [comment]
Any updates on this? I see it was assigned so that's good.

**Comment by jzavala-YYG** [comment]
Hi @FuseGamesLLC I can't replicate this issue using **_IDE v2024.4.1.152  Runtime v2024.4.1.202_**

**Comment by FuseGamesLLC** [comment]
> Hi @FuseGamesLLC I can't replicate this issue using **_IDE v2024.4.1.152 Runtime v2024.4.1.202_**

OK thanks for the reply, I'll try experimenting with my project more to see if it really is an extension conflict or try to narrow it down some. Thanks!

**Comment by FuseGamesLLC** [comment]
I finally figured it out, my podfile wasn't able to find the links to newer pods, but it's fixed after running a pod update. All good now, apologies for opening the issue but if anyone else is out there and has been building on their device for a while, make sure you run pod update every once in a while!
